// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7qfgJ-HLCXCzSL4zOejspIDjXsDmLwow',
    appId: '1:63308558625:web:4bac72e384ec225fde4e60',
    messagingSenderId: '63308558625',
    projectId: 'authentication-9accf',
    authDomain: 'authentication-9accf.firebaseapp.com',
    storageBucket: 'authentication-9accf.appspot.com',
    measurementId: 'G-WR850RNVS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-zxmxPPrCluU7uz2nYalLMKTM2L0uYo0',
    appId: '1:63308558625:android:47a6a4d91930d6a9de4e60',
    messagingSenderId: '63308558625',
    projectId: 'authentication-9accf',
    storageBucket: 'authentication-9accf.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7qfgJ-HLCXCzSL4zOejspIDjXsDmLwow',
    appId: '1:63308558625:web:4bac72e384ec225fde4e60',
    messagingSenderId: '63308558625',
    projectId: 'authentication-9accf',
    authDomain: 'authentication-9accf.firebaseapp.com',
    storageBucket: 'authentication-9accf.appspot.com',
    measurementId: 'G-WR850RNVS5',
  );
}
